// PDF generation using @react-pdf/renderer
// React components render directly to PDF — same component model as the UI

import { renderToBuffer } from '@react-pdf/renderer';
import React from 'react';
import { Document, Page, Text, View, StyleSheet } from '@react-pdf/renderer';

const styles = StyleSheet.create({
  page: { padding: 40, fontSize: 11, fontFamily: 'Helvetica' },
  header: { fontSize: 20, marginBottom: 20, textAlign: 'center' },
  subheader: { fontSize: 14, marginBottom: 10, marginTop: 15, color: '#333' },
  row: { flexDirection: 'row', borderBottomWidth: 1, borderColor: '#eee', paddingVertical: 6 },
  cell: { flex: 1 },
  cellLabel: { flex: 1, fontFamily: 'Helvetica-Bold' },
  footer: { position: 'absolute', bottom: 30, left: 40, right: 40, fontSize: 9, color: '#999', textAlign: 'center' },
});

// ── Procurement Report ─────────────────────────────────────────

interface ReportData {
  title: string;
  org_name: string;
  period: { start: string; end: string };
  tenders: { number: string; title: string; status: string; value: string }[];
  spend_by_category: { category: string; amount: string; count: number }[];
}

function ProcurementReport({ data }: { data: ReportData }) {
  return React.createElement(Document, null,
    React.createElement(Page, { size: 'A4', style: styles.page },
      React.createElement(Text, { style: styles.header }, data.title),
      React.createElement(Text, null, `Organisation: ${data.org_name}`),
      React.createElement(Text, null, `Period: ${data.period.start} to ${data.period.end}`),
      React.createElement(Text, { style: styles.subheader }, 'Tenders'),
      ...data.tenders.map((t, i) =>
        React.createElement(View, { key: i, style: styles.row },
          React.createElement(Text, { style: styles.cellLabel }, t.number),
          React.createElement(Text, { style: styles.cell }, t.title),
          React.createElement(Text, { style: styles.cell }, t.status),
          React.createElement(Text, { style: styles.cell }, t.value),
        )
      ),
      React.createElement(Text, { style: styles.subheader }, 'Spend by Category'),
      ...data.spend_by_category.map((c, i) =>
        React.createElement(View, { key: i, style: styles.row },
          React.createElement(Text, { style: styles.cellLabel }, c.category),
          React.createElement(Text, { style: styles.cell }, c.amount),
          React.createElement(Text, { style: styles.cell }, `${c.count} contracts`),
        )
      ),
      React.createElement(Text, { style: styles.footer },
        `Generated by RFQ Hub on ${new Date().toISOString().split('T')[0]}`
      ),
    )
  );
}

// ── Export Functions ────────────────────────────────────────────

export const pdfService = {
  async generateProcurementReport(data: ReportData): Promise<Buffer> {
    const element = React.createElement(ProcurementReport, { data });
    const buffer = await renderToBuffer(element as any);
    return Buffer.from(buffer);
  },

  async generateEvaluationReport(data: {
    tender_number: string;
    tender_title: string;
    results: { vendor: string; score: string; passed: boolean }[];
  }): Promise<Buffer> {
    const element = React.createElement(Document, null,
      React.createElement(Page, { size: 'A4', style: styles.page },
        React.createElement(Text, { style: styles.header }, `Evaluation Report: ${data.tender_number}`),
        React.createElement(Text, null, data.tender_title),
        React.createElement(Text, { style: styles.subheader }, 'Results'),
        ...data.results.map((r, i) =>
          React.createElement(View, { key: i, style: styles.row },
            React.createElement(Text, { style: styles.cellLabel }, r.vendor),
            React.createElement(Text, { style: styles.cell }, `${r.score}%`),
            React.createElement(Text, { style: styles.cell }, r.passed ? 'PASSED' : 'FAILED'),
          )
        ),
      )
    );
    const buffer = await renderToBuffer(element as any);
    return Buffer.from(buffer);
  },
};
